import { ERROR__EXPLICIT_IDENTITY_FUNCTION_REQUIRED } from "./components/errors/ERROR__EXPLICIT_IDENTITY_FUNCTION_REQUIRED";
import { ERROR__RETROSPECTIVE_TYPE_MISMATCH } from "./components/errors/ERROR__RETROSPECTIVE_TYPE_MISMATCH";

export type TypeErrorMetaLiterals = {
  needIdentityFunction: ERROR__EXPLICIT_IDENTITY_FUNCTION_REQUIRED;
  typeMismatch: ERROR__RETROSPECTIVE_TYPE_MISMATCH;
};
